# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variavel',
            name='codigo_ana',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
