# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_variavel_codigo_ana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serietemporal',
            name='dado',
            field=models.FloatField(null=True),
        ),
    ]
