# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20170217_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posto',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
