# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20170304_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriereduzida',
            name='serie_temporal_id',
            field=models.IntegerField(),
        ),
    ]
