# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20170304_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='discretizacao',
            name='codigo_pandas',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
